### ISSUE TITLE
No need to identify electorates again after already having registered

### ISSUE THREAD

**Issue by vteague** [RightToAskOrg/righttoask-app#31]
When I've already registered, then closed the app, then opened it up again, it seems to remember my ID and keys fine (good). However, it doesn't seem to be dealing with electorates quite right - not sure whether it's not storing them, not retrieving them, or not using them.

Current behaviour: when I'm already registered, but have closed the app and opened it again, when I click on "My MP", either for asking or answering the question, it takes me through the 'find your electorates... ' flow again (Registerpage2) (bad/unnecessary).

Expected behaviour: should be exactly the same as if I registered and then didn't close the app (in which case I'm pretty sure it's already functioning correctly). If we already know who my MPs are, and I click on "My MP", it should just take me straight to a list of my MPs.

**Comment by msl5994** [comment]
Should be fixed via #36
