### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by vteague** [RightToAskOrg/righttoask-app#8]

**Comment by vteague** [comment]
Suppose I make an account (e.g. when I try to upload a question for the first time) without previously having selected my MPs (e.g. if I've selected a public authority to answer the question and 'don't know' to raise it).

In this case, I get taken through RegisterPage1 (good), then onto RegisterPage2 (also good).

Current behaviour:
The problem is that after RegisterPage2 it pushes an Exploring Page with a list of my MPs and invites me to select one. At this point in the flow, that doesn't make sense.

Expected behaviour:
Originally I wasn't intending to push the MPs-ExploringPage at all. So one option would be simply to alter the flow so it doesn't get pushed.

However, an alternative (which might be better) is to push the page, but suppress the selection toggles (which don't make sense) and change some of the text to say "these are your MPs" (remove the text asking you to select one) and change the 'done' button to 'OK' or something else that implies you received information but don't have to do anything about it.

After that, it would make a lot of sense to pop all three pages (leading back to the page where I was trying to submit a question).

**Comment by vteague** [comment]
Decision: Let's just not push that MPs Exploring page.

**Comment by msl5994** [comment]
I'll need to know back on RegisterPage1 that we are coming to the register2 page to not Push an ExploringMPsPage after selecting the electorates. Add a pop upon account creation success back to the QuestionDetailsPage.
